export const currencies = [
  { code: "AED", label_ar: "درهم إماراتي", label_en: "UAE Dirham" },
  { code: "LBP", label_ar: "ليرة لبنانية", label_en: "Lebanese Pound" },
  { code: "USD", label_ar: "دولار أمريكي", label_en: "US Dollar" },
  { code: "BHD", label_ar: "دينار بحريني", label_en: "Bahraini Dinar" },
  { code: "KWD", label_ar: "دينار كويتي", label_en: "Kuwaiti Dinar" },
  { code: "JOD", label_ar: "دينار أردني", label_en: "Jordanian Dinar" },
  { code: "OMR", label_ar: "ريال عماني", label_en: "Omani Rial" },
  { code: "QAR", label_ar: "ريال قطري", label_en: "Qatari Riyal" },
  { code: "SAR", label_ar: "ريال سعودي", label_en: "Saudi Riyal" },
  { code: "EGP", label_ar: "جنيه مصري", label_en: "Egyptian Pound" },
  { code: "EUR", label_ar: "يورو", label_en: "Euro" },
  { code: "GBP", label_ar: "جنيه إسترليني", label_en: "British Pound" },
  { code: "LKR", label_ar: "روبية سريلانكية", label_en: "Sri Lankan Rupee" },
  { code: "NPR", label_ar: "روبية نيبالية", label_en: "Nepalese Rupee" },
  { code: "BDT", label_ar: "تاكا بنغلاديشي", label_en: "Bangladeshi Taka" },
  { code: "PKR", label_ar: "روبية باكستانية", label_en: "Pakistani Rupee" },
  { code: "PHP", label_ar: "بيزو فلبيني", label_en: "Philippine Peso" },
  { code: "INR", label_ar: "روبية هندية", label_en: "Indian Rupee" },
];
